config/routes.rb
Rails.application.routes.draw do
  resources :touches
  resources :deals
  resources :campaigns
  resources :leads
  resources :projects
  resources :companies
  resources :todos
  resources :addresses
  resources :contacts
  devise_for :views
  root to: 'visitors#index'
  devise_for :users
  resources :users
  get "/:page" => "pages#show"
  get '/home' => "pages#home", as: :user_root
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :addressable, polymorphic: true
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  belongs_to :user
  belongs_to :todo
  belongs_to :company
  belongs_to :project
  belongs_to :campaignable, polymorphic: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :companyable, polymorphic: true
  has_many :address, as: :addressable
  has_many :comments, as: :commentable
  has_many :todos, as: :todoable
  has_and_belongs_to_many :contacts
  has_and_belongs_to_many :projects
end

app/models/contact.rb
class Contact < ApplicationRecord
  has_many :address, as: :addressable
  has_many :comments, as: :commentable
  has_many :todos, as: :todoable
  has_and_belongs_to_many :projects
 has_and_belongs_to_many :companies
end

app/models/deal.rb
class Deal < ApplicationRecord
  belongs_to :user
  belongs_to :todo
  belongs_to :company
  belongs_to :dealable, polymorphic: true
end

app/models/lead.rb
class Lead < ApplicationRecord
  belongs_to :leadable, polymorphic: true
  belongs_to :user
end

app/models/project.rb
class Project < ApplicationRecord
  has_and_belongs_to_many :users
  has_many :address, as: :addressable
  has_many :comments, as: :commentable
  has_many :todos, as: :todoable
  has_and_belongs_to_many :contacts
  has_and_belongs_to_many :companies
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :todoable, polymorphic: true
  has_many :comments, as: :commentable
  has_and_belongs_to_many :users
end

app/models/touch.rb
class Touch < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :address, as: :addressable
  has_many :comments, as: :commentable
  has_and_belongs_to_many :todos
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  before_action :set_deal, only: [:show, :edit, :update, :destroy]

  # GET /deals
  # GET /deals.json
  def index
    @deals = Deal.all
  end

  # GET /deals/1
  # GET /deals/1.json
  def show
  end

  # GET /deals/new
  def new
    @deal = Deal.new
  end

  # GET /deals/1/edit
  def edit
  end

  # POST /deals
  # POST /deals.json
  def create
    @deal = Deal.new(deal_params)

    respond_to do |format|
      if @deal.save
        format.html { redirect_to @deal, notice: 'Deal was successfully created.' }
        format.json { render :show, status: :created, location: @deal }
      else
        format.html { render :new }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /deals/1
  # PATCH/PUT /deals/1.json
  def update
    respond_to do |format|
      if @deal.update(deal_params)
        format.html { redirect_to @deal, notice: 'Deal was successfully updated.' }
        format.json { render :show, status: :ok, location: @deal }
      else
        format.html { render :edit }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deals/1
  # DELETE /deals/1.json
  def destroy
    @deal.destroy
    respond_to do |format|
      format.html { redirect_to deals_url, notice: 'Deal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deal
      @deal = Deal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def deal_params
      params.require(:deal).permit(:name, :company, :commission, :time_of_close, :user_id, :todo_id, :company_id, :dealable_id, :dealable_type)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/touches_helper.rb
module TouchesHelper
end

app/views/deals/_form.html.erb
<%= simple_form_for(@deal) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :company %>
    <%= f.input :commission %>
    <%= f.input :time_of_close %>
    <%= f.association :user %>
    <%= f.association :todo %>
    <%= f.association :company %>
    <%= f.association :dealable %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/deals/edit.html.erb
<%= render '/layouts/sidebar'  %>
<%= render 'layouts/navigation'  %>
<div class="container-8">

<h1>Editing Deal</h1>

<%= render 'form', deal: @deal %>

<%= link_to 'Show', @deal %> |
<%= link_to 'Back', deals_path %>
</div>

app/views/deals/index.html.erb
<%= render '/layouts/sidebar'  %>
<%= render 'layouts/navigation'  %>
<div class="container-8">

<p id="notice"><%= notice %></p>

<h1>Deals</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Company</th>
      <th>Commission</th>
      <th>Time of close</th>
      <th>User</th>
      <th>Todo</th>
      <th>Company</th>
      <th>Dealable</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @deals.each do |deal| %>
      <tr>
        <td><%= deal.name %></td>
        <td><%= deal.company %></td>
        <td><%= deal.commission %></td>
        <td><%= deal.time_of_close %></td>
        <td><%= deal.user %></td>
        <td><%= deal.todo %></td>
        <td><%= deal.company %></td>
        <td><%= deal.dealable %></td>
        <td><%= link_to 'Show', deal %></td>
        <td><%= link_to 'Edit', edit_deal_path(deal) %></td>
        <td><%= link_to 'Destroy', deal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Deal', new_deal_path %>
</div>

app/views/deals/new.html.erb
<%= render '/layouts/sidebar'  %>
<%= render 'layouts/navigation'  %>
<div class="container-8">

<h1>New Deal</h1>

<%= render 'form', deal: @deal %>

<%= link_to 'Back', deals_path %>
</div>

app/views/deals/show.html.erb
<%= render '/layouts/sidebar'  %>
<%= render 'layouts/navigation'  %>
<div class="container-8">

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @deal.name %>
</p>

<p>
  <strong>Company:</strong>
  <%= @deal.company %>
</p>

<p>
  <strong>Commission:</strong>
  <%= @deal.commission %>
</p>

<p>
  <strong>Time of close:</strong>
  <%= @deal.time_of_close %>
</p>

<p>
  <strong>User:</strong>
  <%= @deal.user %>
</p>

<p>
  <strong>Todo:</strong>
  <%= @deal.todo %>
</p>

<p>
  <strong>Company:</strong>
  <%= @deal.company %>
</p>

<p>
  <strong>Dealable:</strong>
  <%= @deal.dealable %>
</p>

<%= link_to 'Edit', edit_deal_path(@deal) %> |
<%= link_to 'Back', deals_path %>
</div>