config/routes.rb
Rails.application.routes.draw do
  resources :touches
  resources :deals
  resources :campaigns
  resources :leads
  resources :projects
  resources :companies
  resources :todos
  resources :addresses
  resources :contacts
  devise_for :views
  root to: 'visitors#index'
  devise_for :users
  resources :users
  get "/:page" => "pages#show"
  get '/home' => "pages#home", as: :user_root
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :addressable, polymorphic: true
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  belongs_to :user
  belongs_to :todo
  belongs_to :company
  belongs_to :project
  belongs_to :campaignable, polymorphic: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :companyable, polymorphic: true
  has_many :address, as: :addressable
  has_many :comments, as: :commentable
  has_many :todos, as: :todoable
  has_and_belongs_to_many :contacts
  has_and_belongs_to_many :projects
end

app/models/contact.rb
class Contact < ApplicationRecord
  has_many :address, as: :addressable
  has_many :comments, as: :commentable
  has_many :todos, as: :todoable
  has_and_belongs_to_many :projects
 has_and_belongs_to_many :companies
end

app/models/deal.rb
class Deal < ApplicationRecord
  belongs_to :user
  belongs_to :todo
  belongs_to :company
  belongs_to :dealable, polymorphic: true
end

app/models/lead.rb
class Lead < ApplicationRecord
  belongs_to :leadable, polymorphic: true
  belongs_to :user
end

app/models/project.rb
class Project < ApplicationRecord
  has_and_belongs_to_many :users
  has_many :address, as: :addressable
  has_many :comments, as: :commentable
  has_many :todos, as: :todoable
  has_and_belongs_to_many :contacts
  has_and_belongs_to_many :companies
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :todoable, polymorphic: true
  has_many :comments, as: :commentable
  has_and_belongs_to_many :users
end

app/models/touch.rb
class Touch < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :address, as: :addressable
  has_many :comments, as: :commentable
  has_and_belongs_to_many :todos
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/touches_controller.rb
class TouchesController < ApplicationController
  before_action :set_touch, only: [:show, :edit, :update, :destroy]

  # GET /touches
  # GET /touches.json
  def index
    @touches = Touch.all
  end

  # GET /touches/1
  # GET /touches/1.json
  def show
  end

  # GET /touches/new
  def new
    @touch = Touch.new
  end

  # GET /touches/1/edit
  def edit
  end

  # POST /touches
  # POST /touches.json
  def create
    @touch = Touch.new(touch_params)

    respond_to do |format|
      if @touch.save
        format.html { redirect_to @touch, notice: 'Touch was successfully created.' }
        format.json { render :show, status: :created, location: @touch }
      else
        format.html { render :new }
        format.json { render json: @touch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /touches/1
  # PATCH/PUT /touches/1.json
  def update
    respond_to do |format|
      if @touch.update(touch_params)
        format.html { redirect_to @touch, notice: 'Touch was successfully updated.' }
        format.json { render :show, status: :ok, location: @touch }
      else
        format.html { render :edit }
        format.json { render json: @touch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /touches/1
  # DELETE /touches/1.json
  def destroy
    @touch.destroy
    respond_to do |format|
      format.html { redirect_to touches_url, notice: 'Touch was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_touch
      @touch = Touch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def touch_params
      params.require(:touch).permit(:name, :way_of_contact, :success, :date_touched)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/touches_helper.rb
module TouchesHelper
end

app/views/touches/_form.html.erb
<%= simple_form_for(@touch) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :way_of_contact %>
    <%= f.input :success %>
    <%= f.input :date_touched %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/touches/edit.html.erb
<%= render '/layouts/sidebar'  %>
<%= render 'layouts/navigation'  %>
<div class="container-8">
<h1>Editing Touch</h1>

<%= render 'form', touch: @touch %>

<%= link_to 'Show', @touch %> |
<%= link_to 'Back', touches_path %>
</div>

app/views/touches/index.html.erb
<%= render '/layouts/sidebar'  %>
<%= render 'layouts/navigation'  %>
<div class="container-8">
<p id="notice"><%= notice %></p>

<h1>Touches</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Way of contact</th>
      <th>Success</th>
      <th>Date touched</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @touches.each do |touch| %>
      <tr>
        <td><%= touch.name %></td>
        <td><%= touch.way_of_contact %></td>
        <td><%= touch.success %></td>
        <td><%= touch.date_touched %></td>
        <td><%= link_to 'Show', touch %></td>
        <td><%= link_to 'Edit', edit_touch_path(touch) %></td>
        <td><%= link_to 'Destroy', touch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Touch', new_touch_path %>
</div>

app/views/touches/new.html.erb
<%= render '/layouts/sidebar'  %>
<%= render 'layouts/navigation'  %>
<div class="container-8">
<h1>New Touch</h1>

<%= render 'form', touch: @touch %>

<%= link_to 'Back', touches_path %>
</div>

app/views/touches/show.html.erb
<%= render '/layouts/sidebar'  %>
<%= render 'layouts/navigation'  %>
<div class="container-8">
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @touch.name %>
</p>

<p>
  <strong>Way of contact:</strong>
  <%= @touch.way_of_contact %>
</p>

<p>
  <strong>Success:</strong>
  <%= @touch.success %>
</p>

<p>
  <strong>Date touched:</strong>
  <%= @touch.date_touched %>
</p>

<%= link_to 'Edit', edit_touch_path(@touch) %> |
<%= link_to 'Back', touches_path %>
</div>